In [1]:
import pandas as pd

In [2]:
data = {
    'Refund' : ['Yes','No','No','Yes','No','No','Yes','No','No','No'],
    'Marital Status' : ['Single','Married','Single','Married','Divorced', 'Married','Divorced','Single','Married','Single'],
    'Taxable Income' :['125K','100K','70K','120K','95K','60K','220K','85K','75K','90K'],
    'Cheat':['No','No','No','No','Yes','No','No','Yes','No','Yes']
}
df=pd.DataFrame(data)
df

  Refund Marital Status Taxable Income Cheat
0    Yes         Single           125K    No
1     No        Married           100K    No
2     No         Single            70K    No
3    Yes        Married           120K    No
4     No       Divorced            95K   Yes
5     No        Married            60K    No
6    Yes       Divorced           220K    No
7     No         Single            85K   Yes
8     No        Married            75K    No
9     No         Single            90K   Yes

In [3]:
print(df.loc[0])
print(df.loc[4])
print(df.loc[7:8])

Refund               Yes
Marital Status    Single
Taxable Income      125K
Cheat                 No
Name: 0, dtype: object
Refund                  No
Marital Status    Divorced
Taxable Income         95K
Cheat                  Yes
Name: 4, dtype: object
  Refund Marital Status Taxable Income Cheat
7     No         Single            85K   Yes
8     No        Married            75K    No

In [4]:
print(df.loc[3:7])
print(df.iloc[3:7, 2:4])
print(df.iloc[:, 1:4])

  Refund Marital Status Taxable Income Cheat
3    Yes        Married           120K    No
4     No       Divorced            95K   Yes
5     No        Married            60K    No
6    Yes       Divorced           220K    No
7     No         Single            85K   Yes
  Taxable Income Cheat
3           120K    No
4            95K   Yes
5            60K    No
6           220K    No
  Marital Status Taxable Income Cheat
0         Single           125K    No
1        Married           100K    No
2         Single            70K    No
3        Married           120K    No
4       Divorced            95K   Yes
5        Married            60K    No
6       Divorced           220K    No
7         Single            85K   Yes
8        Married            75K    No
9         Single            90K   Yes

In [7]:
df1=pd.read_csv('iris.csv')
print(df1)

FileNotFoundError: [Errno 2] No such file or directory: 'iris.csv'

Since you uploaded `iris.csv` to the Colab notebook's files section, it should be in the current working directory, typically `/content/`. Let's try reading it directly.

In [19]:
df_iris = pd.read_csv('/tmp/iris.csv')
display(df_iris.head())

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [21]:
df_iris.drop(4,axis=0, inplace=True)
df_iris.drop(df_iris.columns[3],axis=1, inplace=True)
df_iris

     sepal.length  sepal.width  petal.length
0             5.1          3.5           1.4
1             4.9          3.0           1.4
2             4.7          3.2           1.3
3             4.6          3.1           1.5
5             5.4          3.9           1.7
..            ...          ...           ...
145           6.7          3.0           5.2
146           6.3          2.5           5.0
147           6.5          3.0           5.2
148           6.2          3.4           5.4
149           5.9          3.0           5.1

[149 rows x 3 columns]

In [34]:
df_emp = pd.read_csv('/Employees.csv')
display(df_emp.head())

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,15-03-2020,Female,5000,4.5
1,102,Bob,IT,34,70000,8,19-07-2017,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,01-06-2013,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,10-02-2021,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,25-11-2010,Male,5000,3.5

In [35]:
df_emp.shape

(5, 10)

In [36]:
df_emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

In [37]:
df_emp.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

In [38]:
print(df_emp.head(5))
print(df_emp.tail(3))

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   15-03-2020  Female   5000     4.5
1   19-07-2017    Male   7000     4.0
2   01-06-2013    Male   6000     3.8
3   10-02-2021  Female   4500     4.7
4   25-11-2010    Male   5000     3.5
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
2   01-06-2013    Male   6000     3.8
3   10-02-2021  Female   4500     4.7
4   25-11-2010    Male   5000     3.5

In [39]:
avg_salary = df_emp["Salary"].mean()
total_bonus=df_emp["Bonus"].sum()
youngest_age=df_emp["Age"].min()
highest_rating = df_emp["Rating"].max()
print("Average Salary:", avg_salary)
print("Total Bonus:", total_bonus)
print("Youngest Age:", youngest_age)
print("Highest Rating:", highest_rating)

Average Salary: 60000.0
Total Bonus: 27500
Youngest Age: 28
Highest Rating: 4.7

In [41]:
df_sorted=df_emp.sort_values(by="Salary",ascending=False)
df_sorted

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,19-07-2017,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,01-06-2013,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,25-11-2010,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,10-02-2021,Female,4500,4.7
0,101,Alice,HR,29,50000,4,15-03-2020,Female,5000,4.5

In [43]:
def categorise_rating(rating):
  if rating>=4.5:
    return "Excellent"
  elif rating >= 4.0:
    return "Good"
  else:
    return "Average"

df_emp["Performance_Category"] = df_emp["Rating"].apply(categorise_rating)
print(df_emp)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating Performance_Category
0   15-03-2020  Female   5000     4.5            Excellent
1   19-07-2017    Male   7000     4.0                 Good
2   01-06-2013    Male   6000     3.8              Average
3   10-02-2021  Female   4500     4.7            Excellent
4   25-11-2010    Male   5000     3.5              Average

In [44]:
print(df_emp.isnull().sum())

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

In [45]:
df_emp.rename(columns={"Employee_ID":"ID"},inplace=True)

In [47]:
exp_gt_5=df_emp[df_emp["Years_of_Experience"]>5]
print(exp_gt_5)
it_dept=df_emp[df_emp["Department"]== 'IT']
print(it_dept)

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   19-07-2017
2  103  Charlie         IT   41   65000                   10   01-06-2013
4  105   Edward      Sales   38   60000                   12   25-11-2010

  Gender  Bonus  Rating Performance_Category
1   Male   7000     4.0                 Good
2   Male   6000     3.8              Average
4   Male   5000     3.5              Average
    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   19-07-2017
2  103  Charlie         IT   41   65000                   10   01-06-2013

  Gender  Bonus  Rating Performance_Category
1   Male   7000     4.0                 Good
2   Male   6000     3.8              Average

In [50]:
df_emp["Tax"] = df_emp["Salary"] * 0.10
print(df_emp)

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
0  101    Alice         HR   29   50000                    4   15-03-2020
1  102      Bob         IT   34   70000                    8   19-07-2017
2  103  Charlie         IT   41   65000                   10   01-06-2013
3  104    Diana  Marketing   28   55000                    3   10-02-2021
4  105   Edward      Sales   38   60000                   12   25-11-2010

   Gender  Bonus  Rating Performance_Category     Tax
0  Female   5000     4.5            Excellent  5000.0
1    Male   7000     4.0                 Good  7000.0
2    Male   6000     3.8              Average  6500.0
3  Female   4500     4.7            Excellent  5500.0
4    Male   5000     3.5              Average  6000.0

In [49]:
df_emp.to_csv("Updated_Employees.csv",index=False)